export const matches = {
  api: {
    results: 130,
    fixtures: {
      "30660": {
        fixture_id: "30660",
        event_timestamp: "1547274900",
        event_date: "2019-01-12T06:35:00+00:00",
        league_id: "105",
        round: "A-League - 13",
        homeTeam_id: "942",
        awayTeam_id: "941",
        homeTeam: "Wellington Phoenix",
        awayTeam: "Central Coast Mariners FC",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "66273": {
        fixture_id: "66273",
        event_timestamp: "1547281800",
        event_date: "2019-01-12T08:30:00+00:00",
        league_id: "243",
        round: "W-League - Round 11",
        homeTeam_id: "1975",
        awayTeam_id: "1969",
        homeTeam: "Newcastle Jets FC W",
        awayTeam: "Perth Glory FC W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "30661": {
        fixture_id: "30661",
        event_timestamp: "1547283000",
        event_date: "2019-01-12T08:50:00+00:00",
        league_id: "105",
        round: "A-League - 13",
        homeTeam_id: "944",
        awayTeam_id: "946",
        homeTeam: "Melbourne Victory",
        awayTeam: "Newcastle Jets FC",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "55742": {
        fixture_id: "55742",
        event_timestamp: "1547290800",
        event_date: "2019-01-12T11:00:00+00:00",
        league_id: "195",
        round: "Asian Cup Grp. D - Matchday 2",
        homeTeam_id: "1542",
        awayTeam_id: "22",
        homeTeam: "Vietnam",
        awayTeam: "Iran",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39394": {
        fixture_id: "39394",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 23",
        homeTeam_id: "926",
        awayTeam_id: "924",
        homeTeam: "El Eulma",
        awayTeam: "ASM Oran",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39396": {
        fixture_id: "39396",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 23",
        homeTeam_id: "933",
        awayTeam_id: "923",
        homeTeam: "JSM Skikda",
        awayTeam: "Amal BOU Saada",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39397": {
        fixture_id: "39397",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 23",
        homeTeam_id: "934",
        awayTeam_id: "909",
        homeTeam: "MC Saida",
        awayTeam: "US Biskra",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39398": {
        fixture_id: "39398",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 23",
        homeTeam_id: "1070",
        awayTeam_id: "1069",
        homeTeam: "Mostaganem",
        awayTeam: "USM Annaba",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39399": {
        fixture_id: "39399",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 23",
        homeTeam_id: "1071",
        awayTeam_id: "912",
        homeTeam: "NC Magra",
        awayTeam: "Blida",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39360": {
        fixture_id: "39360",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 18",
        homeTeam_id: "1069",
        awayTeam_id: "912",
        homeTeam: "USM Annaba",
        awayTeam: "Blida",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39359": {
        fixture_id: "39359",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 18",
        homeTeam_id: "921",
        awayTeam_id: "933",
        homeTeam: "RC Relizane",
        awayTeam: "JSM Skikda",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39358": {
        fixture_id: "39358",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 18",
        homeTeam_id: "935",
        awayTeam_id: "931",
        homeTeam: "RC Kouba",
        awayTeam: "ASO Chlef",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39357": {
        fixture_id: "39357",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 18",
        homeTeam_id: "1070",
        awayTeam_id: "1071",
        homeTeam: "Mostaganem",
        awayTeam: "NC Magra",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39395": {
        fixture_id: "39395",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 23",
        homeTeam_id: "932",
        awayTeam_id: "931",
        homeTeam: "JSM Bejaia",
        awayTeam: "ASO Chlef",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39356": {
        fixture_id: "39356",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 18",
        homeTeam_id: "926",
        awayTeam_id: "919",
        homeTeam: "El Eulma",
        awayTeam: "Usm El Harrach",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39355": {
        fixture_id: "39355",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 18",
        homeTeam_id: "924",
        awayTeam_id: "932",
        homeTeam: "ASM Oran",
        awayTeam: "JSM Bejaia",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39354": {
        fixture_id: "39354",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 18",
        homeTeam_id: "923",
        awayTeam_id: "909",
        homeTeam: "Amal BOU Saada",
        awayTeam: "US Biskra",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39400": {
        fixture_id: "39400",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 23",
        homeTeam_id: "921",
        awayTeam_id: "928",
        homeTeam: "RC Relizane",
        awayTeam: "WA Tlemcen",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39401": {
        fixture_id: "39401",
        event_timestamp: "1547294400",
        event_date: "2019-01-12T12:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 23",
        homeTeam_id: "919",
        awayTeam_id: "935",
        homeTeam: "Usm El Harrach",
        awayTeam: "RC Kouba",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "284": {
        fixture_id: "284",
        event_timestamp: "1547296200",
        event_date: "2019-01-12T12:30:00+00:00",
        league_id: "2",
        round: "Premier League - 22",
        homeTeam_id: "48",
        awayTeam_id: "42",
        homeTeam: "West Ham",
        awayTeam: "Arsenal",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "64718": {
        fixture_id: "64718",
        event_timestamp: "1547298000",
        event_date: "2019-01-12T13:00:00+00:00",
        league_id: "231",
        round: "Serie A Women - Round 13",
        homeTeam_id: "1880",
        awayTeam_id: "1893",
        homeTeam: "Fiorentina W",
        awayTeam: "AC Milan W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "70947": {
        fixture_id: "70947",
        event_timestamp: "1547298000",
        event_date: "2019-01-12T13:00:00+00:00",
        league_id: "264",
        round: "Football League - Round 12",
        homeTeam_id: "2107",
        awayTeam_id: "2111",
        homeTeam: "Irodotos",
        awayTeam: "AOK Kerkyra",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "64722": {
        fixture_id: "64722",
        event_timestamp: "1547298000",
        event_date: "2019-01-12T13:00:00+00:00",
        league_id: "231",
        round: "Serie A Women - Round 13",
        homeTeam_id: "1883",
        awayTeam_id: "1891",
        homeTeam: "Verona W",
        awayTeam: "Orobica W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "64721": {
        fixture_id: "64721",
        event_timestamp: "1547298000",
        event_date: "2019-01-12T13:00:00+00:00",
        league_id: "231",
        round: "Serie A Women - Round 13",
        homeTeam_id: "1876",
        awayTeam_id: "1892",
        homeTeam: "Tavagnacco W",
        awayTeam: "Roma W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "64720": {
        fixture_id: "64720",
        event_timestamp: "1547298000",
        event_date: "2019-01-12T13:00:00+00:00",
        league_id: "231",
        round: "Serie A Women - Round 13",
        homeTeam_id: "1889",
        awayTeam_id: "1882",
        homeTeam: "Sassuolo W",
        awayTeam: "Mozzanica W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "64719": {
        fixture_id: "64719",
        event_timestamp: "1547298000",
        event_date: "2019-01-12T13:00:00+00:00",
        league_id: "231",
        round: "Serie A Women - Round 13",
        homeTeam_id: "1886",
        awayTeam_id: "1890",
        homeTeam: "Juventus W",
        awayTeam: "Florentia W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "64717": {
        fixture_id: "64717",
        event_timestamp: "1547298000",
        event_date: "2019-01-12T13:00:00+00:00",
        league_id: "231",
        round: "Serie A Women - Round 13",
        homeTeam_id: "1884",
        awayTeam_id: "1887",
        homeTeam: "Bari Pink W",
        awayTeam: "Chievo Verona W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "55743": {
        fixture_id: "55743",
        event_timestamp: "1547299800",
        event_date: "2019-01-12T13:30:00+00:00",
        league_id: "195",
        round: "Asian Cup Grp. D - Matchday 2",
        homeTeam_id: "1550",
        awayTeam_id: "1567",
        homeTeam: "Yemen",
        awayTeam: "Iraq",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "57871": {
        fixture_id: "57871",
        event_timestamp: "1547299800",
        event_date: "2019-01-12T13:30:00+00:00",
        league_id: "207",
        round: "Feminine Division 1 - Round 15",
        homeTeam_id: "1676",
        awayTeam_id: "1677",
        homeTeam: "Paris FC W",
        awayTeam: "FC Fleury 91 W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "57870": {
        fixture_id: "57870",
        event_timestamp: "1547299800",
        event_date: "2019-01-12T13:30:00+00:00",
        league_id: "207",
        round: "Feminine Division 1 - Round 15",
        homeTeam_id: "1675",
        awayTeam_id: "1669",
        homeTeam: "Montpellier W",
        awayTeam: "Soyaux W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "57869": {
        fixture_id: "57869",
        event_timestamp: "1547299800",
        event_date: "2019-01-12T13:30:00+00:00",
        league_id: "207",
        round: "Feminine Division 1 - Round 15",
        homeTeam_id: "1664",
        awayTeam_id: "1672",
        homeTeam: "Metz W",
        awayTeam: "Guingamp W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "57868": {
        fixture_id: "57868",
        event_timestamp: "1547299800",
        event_date: "2019-01-12T13:30:00+00:00",
        league_id: "207",
        round: "Feminine Division 1 - Round 15",
        homeTeam_id: "1674",
        awayTeam_id: "1668",
        homeTeam: "Lyon W",
        awayTeam: "Rodez W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "57867": {
        fixture_id: "57867",
        event_timestamp: "1547299800",
        event_date: "2019-01-12T13:30:00+00:00",
        league_id: "207",
        round: "Feminine Division 1 - Round 15",
        homeTeam_id: "1678",
        awayTeam_id: "1667",
        homeTeam: "Lille W",
        awayTeam: "Paris Saint Germain W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "57866": {
        fixture_id: "57866",
        event_timestamp: "1547299800",
        event_date: "2019-01-12T13:30:00+00:00",
        league_id: "207",
        round: "Feminine Division 1 - Round 15",
        homeTeam_id: "1671",
        awayTeam_id: "1679",
        homeTeam: "Bordeaux W",
        awayTeam: "Dijon W",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39353": {
        fixture_id: "39353",
        event_timestamp: "1547301600",
        event_date: "2019-01-12T14:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 17",
        homeTeam_id: "919",
        awayTeam_id: "1070",
        homeTeam: "Usm El Harrach",
        awayTeam: "Mostaganem",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39351": {
        fixture_id: "39351",
        event_timestamp: "1547301600",
        event_date: "2019-01-12T14:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 17",
        homeTeam_id: "934",
        awayTeam_id: "921",
        homeTeam: "MC Saida",
        awayTeam: "RC Relizane",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39348": {
        fixture_id: "39348",
        event_timestamp: "1547301600",
        event_date: "2019-01-12T14:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 17",
        homeTeam_id: "912",
        awayTeam_id: "924",
        homeTeam: "Blida",
        awayTeam: "ASM Oran",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39346": {
        fixture_id: "39346",
        event_timestamp: "1547301600",
        event_date: "2019-01-12T14:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 17",
        homeTeam_id: "923",
        awayTeam_id: "1071",
        homeTeam: "Amal BOU Saada",
        awayTeam: "NC Magra",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "65923": {
        fixture_id: "65923",
        event_timestamp: "1547301600",
        event_date: "2019-01-12T14:00:00+00:00",
        league_id: "198",
        round: "Third Round - 1/8",
        homeTeam_id: "487",
        awayTeam_id: "513",
        homeTeam: "Lazio",
        awayTeam: "Novara",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "1550": {
        fixture_id: "1550",
        event_timestamp: "1547301600",
        event_date: "2019-01-12T14:00:00+00:00",
        league_id: "5",
        round: "Ligue 2 - 20",
        homeTeam_id: "101",
        awayTeam_id: "111",
        homeTeam: "Grenoble",
        awayTeam: "LE Havre",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "1555": {
        fixture_id: "1555",
        event_timestamp: "1547301600",
        event_date: "2019-01-12T14:00:00+00:00",
        league_id: "5",
        round: "Ligue 2 - 20",
        homeTeam_id: "106",
        awayTeam_id: "110",
        homeTeam: "Stade Brestois 29",
        awayTeam: "Estac Troyes",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "5422": {
        fixture_id: "5422",
        event_timestamp: "1547303400",
        event_date: "2019-01-12T14:30:00+00:00",
        league_id: "17",
        round: "Welsh Premier League - 22",
        homeTeam_id: "359",
        awayTeam_id: "357",
        homeTeam: "Carmarthen Town",
        awayTeam: "GAP Connah S Quay FC",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "5420": {
        fixture_id: "5420",
        event_timestamp: "1547303400",
        event_date: "2019-01-12T14:30:00+00:00",
        league_id: "17",
        round: "Welsh Premier League - 22",
        homeTeam_id: "352",
        awayTeam_id: "356",
        homeTeam: "Bala Town",
        awayTeam: "Caernarfon Town",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "5421": {
        fixture_id: "5421",
        event_timestamp: "1547303400",
        event_date: "2019-01-12T14:30:00+00:00",
        league_id: "17",
        round: "Welsh Premier League - 22",
        homeTeam_id: "361",
        awayTeam_id: "351",
        homeTeam: "Barry Town",
        awayTeam: "Aberystwyth Town",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "5423": {
        fixture_id: "5423",
        event_timestamp: "1547303400",
        event_date: "2019-01-12T14:30:00+00:00",
        league_id: "17",
        round: "Welsh Premier League - 22",
        homeTeam_id: "362",
        awayTeam_id: "353",
        homeTeam: "Llandudno",
        awayTeam: "Cardiff MET",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "5424": {
        fixture_id: "5424",
        event_timestamp: "1547303400",
        event_date: "2019-01-12T14:30:00+00:00",
        league_id: "17",
        round: "Welsh Premier League - 22",
        homeTeam_id: "358",
        awayTeam_id: "360",
        homeTeam: "Newtown AFC",
        awayTeam: "Cefn Druids AFC",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "5425": {
        fixture_id: "5425",
        event_timestamp: "1547303400",
        event_date: "2019-01-12T14:30:00+00:00",
        league_id: "17",
        round: "Welsh Premier League - 22",
        homeTeam_id: "354",
        awayTeam_id: "355",
        homeTeam: "The New Saints",
        awayTeam: "llanelli AFC",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50107": {
        fixture_id: "50107",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1344",
        awayTeam_id: "1348",
        homeTeam: "Bury",
        awayTeam: "Milton Keynes Dons",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "40982": {
        fixture_id: "40982",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "108",
        round: "Super League - 16",
        homeTeam_id: "950",
        awayTeam_id: "575",
        homeTeam: "PAS Giannina",
        awayTeam: "AEK Athens FC",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48462": {
        fixture_id: "48462",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1358",
        awayTeam_id: "1354",
        homeTeam: "Wycombe",
        awayTeam: "Doncaster",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48461": {
        fixture_id: "48461",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1342",
        awayTeam_id: "1340",
        homeTeam: "Walsall",
        awayTeam: "Scunthorpe",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48460": {
        fixture_id: "48460",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "746",
        awayTeam_id: "1359",
        homeTeam: "Sunderland",
        awayTeam: "Luton",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48459": {
        fixture_id: "48459",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1341",
        awayTeam_id: "1357",
        homeTeam: "Southend",
        awayTeam: "Plymouth",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48458": {
        fixture_id: "48458",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1352",
        awayTeam_id: "1335",
        homeTeam: "Shrewsbury",
        awayTeam: "Charlton",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48457": {
        fixture_id: "48457",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1355",
        awayTeam_id: "1356",
        homeTeam: "Portsmouth",
        awayTeam: "Blackpool",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48451": {
        fixture_id: "48451",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1360",
        awayTeam_id: "1334",
        homeTeam: "Accrington ST",
        awayTeam: "Bristol Rovers",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48452": {
        fixture_id: "48452",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "747",
        awayTeam_id: "1343",
        homeTeam: "Barnsley",
        awayTeam: "Bradford",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48453": {
        fixture_id: "48453",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "748",
        awayTeam_id: "1347",
        homeTeam: "Burton Albion",
        awayTeam: "Gillingham",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48454": {
        fixture_id: "48454",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1346",
        awayTeam_id: "1333",
        homeTeam: "Coventry",
        awayTeam: "AFC Wimbledon",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48456": {
        fixture_id: "48456",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1350",
        awayTeam_id: "1339",
        homeTeam: "Peterborough",
        awayTeam: "Rochdale",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "48455": {
        fixture_id: "48455",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "164",
        round: "League One - Round 28",
        homeTeam_id: "1336",
        awayTeam_id: "1338",
        homeTeam: "Fleetwood Town",
        awayTeam: "Oxford United",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50108": {
        fixture_id: "50108",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1372",
        awayTeam_id: "1381",
        homeTeam: "Cheltenham",
        awayTeam: "Tranmere",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50109": {
        fixture_id: "50109",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1363",
        awayTeam_id: "1367",
        homeTeam: "Crewe",
        awayTeam: "Newport County",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50110": {
        fixture_id: "50110",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1364",
        awayTeam_id: "1375",
        homeTeam: "Exeter City",
        awayTeam: "Morecambe",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50795": {
        fixture_id: "50795",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "170",
        round: "Championship - Round 21",
        homeTeam_id: "1391",
        awayTeam_id: "1383",
        homeTeam: "Alloa Athletic",
        awayTeam: "Morton",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50796": {
        fixture_id: "50796",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "170",
        round: "Championship - Round 21",
        homeTeam_id: "1386",
        awayTeam_id: "1388",
        homeTeam: "Dundee Utd",
        awayTeam: "Dunfermline",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50797": {
        fixture_id: "50797",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "170",
        round: "Championship - Round 21",
        homeTeam_id: "903",
        awayTeam_id: "1387",
        homeTeam: "Inverness CT",
        awayTeam: "Ayr Utd",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50799": {
        fixture_id: "50799",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "170",
        round: "Championship - Round 21",
        homeTeam_id: "1384",
        awayTeam_id: "902",
        homeTeam: "Queen of the South",
        awayTeam: "Ross County",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50117": {
        fixture_id: "50117",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1368",
        awayTeam_id: "1362",
        homeTeam: "Stevenage",
        awayTeam: "Crawley Town",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50798": {
        fixture_id: "50798",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "170",
        round: "Championship - Round 21",
        homeTeam_id: "901",
        awayTeam_id: "1389",
        homeTeam: "Partick",
        awayTeam: "Falkirk",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50112": {
        fixture_id: "50112",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1374",
        awayTeam_id: "1377",
        homeTeam: "Mansfield Town",
        awayTeam: "Yeovil Town",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "766": {
        fixture_id: "766",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "62",
        awayTeam_id: "72",
        homeTeam: "Sheffield Utd",
        awayTeam: "QPR",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50116": {
        fixture_id: "50116",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1351",
        awayTeam_id: "1361",
        homeTeam: "Port Vale",
        awayTeam: "Colchester",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50115": {
        fixture_id: "50115",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1349",
        awayTeam_id: "1378",
        homeTeam: "Oldham",
        awayTeam: "Forest Green",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50114": {
        fixture_id: "50114",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1376",
        awayTeam_id: "1370",
        homeTeam: "Notts County",
        awayTeam: "Cambridge United",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50113": {
        fixture_id: "50113",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1337",
        awayTeam_id: "1371",
        homeTeam: "Northampton",
        awayTeam: "Carlisle",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50111": {
        fixture_id: "50111",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1365",
        awayTeam_id: "1380",
        homeTeam: "Grimsby",
        awayTeam: "Macclesfield",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "50118": {
        fixture_id: "50118",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "167",
        round: "League Two - Round 28",
        homeTeam_id: "1353",
        awayTeam_id: "1379",
        homeTeam: "Swindon Town",
        awayTeam: "Lincoln",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "275": {
        fixture_id: "275",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "2",
        round: "Premier League - 22",
        homeTeam_id: "51",
        awayTeam_id: "40",
        homeTeam: "Brighton",
        awayTeam: "Liverpool",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "763": {
        fixture_id: "763",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "58",
        awayTeam_id: "67",
        homeTeam: "Millwall",
        awayTeam: "Blackburn",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "764": {
        fixture_id: "764",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "59",
        awayTeam_id: "76",
        homeTeam: "Preston",
        awayTeam: "Swansea",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "765": {
        fixture_id: "765",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "53",
        awayTeam_id: "65",
        homeTeam: "Reading",
        awayTeam: "Nottingham Forest",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "767": {
        fixture_id: "767",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "60",
        awayTeam_id: "71",
        homeTeam: "West Brom",
        awayTeam: "Norwich",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "768": {
        fixture_id: "768",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "61",
        awayTeam_id: "66",
        homeTeam: "Wigan",
        awayTeam: "Aston Villa",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39734": {
        fixture_id: "39734",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 16",
        homeTeam_id: "963",
        awayTeam_id: "976",
        homeTeam: "Chabab RIF Hoceima",
        awayTeam: "Raja Casablanca",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39735": {
        fixture_id: "39735",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 16",
        homeTeam_id: "964",
        awayTeam_id: "969",
        homeTeam: "Difaa EL Jadida",
        awayTeam: "FAR Rabat",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39736": {
        fixture_id: "39736",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 16",
        homeTeam_id: "977",
        awayTeam_id: "971",
        homeTeam: "FUS Rabat",
        awayTeam: "Kawkab Marrakech",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "762": {
        fixture_id: "762",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "63",
        awayTeam_id: "69",
        homeTeam: "Leeds",
        awayTeam: "Derby",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "761": {
        fixture_id: "761",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "57",
        awayTeam_id: "73",
        homeTeam: "Ipswich",
        awayTeam: "Rotherham",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "276": {
        fixture_id: "276",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "2",
        round: "Premier League - 22",
        homeTeam_id: "44",
        awayTeam_id: "36",
        homeTeam: "Burnley",
        awayTeam: "Fulham",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "277": {
        fixture_id: "277",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "2",
        round: "Premier League - 22",
        homeTeam_id: "43",
        awayTeam_id: "37",
        homeTeam: "Cardiff",
        awayTeam: "Huddersfield",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "279": {
        fixture_id: "279",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "2",
        round: "Premier League - 22",
        homeTeam_id: "52",
        awayTeam_id: "38",
        homeTeam: "Crystal Palace",
        awayTeam: "Watford",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "281": {
        fixture_id: "281",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "2",
        round: "Premier League - 22",
        homeTeam_id: "46",
        awayTeam_id: "41",
        homeTeam: "Leicester",
        awayTeam: "Southampton",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "757": {
        fixture_id: "757",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "54",
        awayTeam_id: "70",
        homeTeam: "Birmingham",
        awayTeam: "Middlesbrough",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "758": {
        fixture_id: "758",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "55",
        awayTeam_id: "75",
        homeTeam: "Brentford",
        awayTeam: "Stoke City",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "759": {
        fixture_id: "759",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "56",
        awayTeam_id: "68",
        homeTeam: "Bristol City",
        awayTeam: "Bolton",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "760": {
        fixture_id: "760",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "3",
        round: "Championship - 27",
        homeTeam_id: "64",
        awayTeam_id: "74",
        homeTeam: "Hull City",
        awayTeam: "Sheffield Wednesday",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39737": {
        fixture_id: "39737",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 16",
        homeTeam_id: "973",
        awayTeam_id: "1074",
        homeTeam: "Hassania Agadir",
        awayTeam: "Youssoufia Berrechid",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39738": {
        fixture_id: "39738",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 16",
        homeTeam_id: "965",
        awayTeam_id: "972",
        homeTeam: "Moghreb Tetouan",
        awayTeam: "Olympique Khouribga",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39777": {
        fixture_id: "39777",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 21",
        homeTeam_id: "972",
        awayTeam_id: "969",
        homeTeam: "Olympique Khouribga",
        awayTeam: "FAR Rabat",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39778": {
        fixture_id: "39778",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 21",
        homeTeam_id: "975",
        awayTeam_id: "964",
        homeTeam: "Olympique Safi",
        awayTeam: "Difaa EL Jadida",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39779": {
        fixture_id: "39779",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 21",
        homeTeam_id: "962",
        awayTeam_id: "976",
        homeTeam: "Renaissance Berkane",
        awayTeam: "Raja Casablanca",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39780": {
        fixture_id: "39780",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 21",
        homeTeam_id: "968",
        awayTeam_id: "965",
        homeTeam: "Wydad AC",
        awayTeam: "Moghreb Tetouan",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39781": {
        fixture_id: "39781",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 21",
        homeTeam_id: "1074",
        awayTeam_id: "967",
        homeTeam: "Youssoufia Berrechid",
        awayTeam: "Rapide Oued ZEM",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "40975": {
        fixture_id: "40975",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "108",
        round: "Super League - 16",
        homeTeam_id: "1123",
        awayTeam_id: "956",
        homeTeam: "Aris Thessalonikis",
        awayTeam: "Lamia",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "40976": {
        fixture_id: "40976",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "108",
        round: "Super League - 16",
        homeTeam_id: "955",
        awayTeam_id: "619",
        homeTeam: "Asteras Tripolis",
        awayTeam: "PAOK",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "40977": {
        fixture_id: "40977",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "108",
        round: "Super League - 16",
        homeTeam_id: "952",
        awayTeam_id: "949",
        homeTeam: "Atromitos Athinon",
        awayTeam: "Panetolikos",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "40978": {
        fixture_id: "40978",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "108",
        round: "Super League - 16",
        homeTeam_id: "953",
        awayTeam_id: "951",
        homeTeam: "Larisa",
        awayTeam: "Apollon Smirnis",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "40979": {
        fixture_id: "40979",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "108",
        round: "Super League - 16",
        homeTeam_id: "957",
        awayTeam_id: "553",
        homeTeam: "Levadiakos",
        awayTeam: "Olympiakos Piraeus",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "40980": {
        fixture_id: "40980",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "108",
        round: "Super League - 16",
        homeTeam_id: "1124",
        awayTeam_id: "622",
        homeTeam: "OFI",
        awayTeam: "Panionios",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39776": {
        fixture_id: "39776",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 21",
        homeTeam_id: "971",
        awayTeam_id: "963",
        homeTeam: "Kawkab Marrakech",
        awayTeam: "Chabab RIF Hoceima",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39775": {
        fixture_id: "39775",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 21",
        homeTeam_id: "974",
        awayTeam_id: "973",
        homeTeam: "Ittihad Tanger",
        awayTeam: "Hassania Agadir",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "40981": {
        fixture_id: "40981",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "108",
        round: "Super League - 16",
        homeTeam_id: "617",
        awayTeam_id: "959",
        homeTeam: "Panathinaikos",
        awayTeam: "Xanthi FC",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39739": {
        fixture_id: "39739",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 16",
        homeTeam_id: "1075",
        awayTeam_id: "962",
        homeTeam: "Mouloudia Oujda",
        awayTeam: "Renaissance Berkane",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39740": {
        fixture_id: "39740",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 16",
        homeTeam_id: "967",
        awayTeam_id: "974",
        homeTeam: "Rapide Oued ZEM",
        awayTeam: "Ittihad Tanger",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39741": {
        fixture_id: "39741",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 16",
        homeTeam_id: "968",
        awayTeam_id: "975",
        homeTeam: "Wydad AC",
        awayTeam: "Olympique Safi",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39774": {
        fixture_id: "39774",
        event_timestamp: "1547305200",
        event_date: "2019-01-12T15:00:00+00:00",
        league_id: "115",
        round: "Botola Pro - 21",
        homeTeam_id: "977",
        awayTeam_id: "1075",
        homeTeam: "FUS Rabat",
        awayTeam: "Mouloudia Oujda",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "39349": {
        fixture_id: "39349",
        event_timestamp: "1547308800",
        event_date: "2019-01-12T16:00:00+00:00",
        league_id: "102",
        round: "Ligue 2 - 17",
        homeTeam_id: "932",
        awayTeam_id: "928",
        homeTeam: "JSM Bejaia",
        awayTeam: "WA Tlemcen",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "55744": {
        fixture_id: "55744",
        event_timestamp: "1547308800",
        event_date: "2019-01-12T16:00:00+00:00",
        league_id: "195",
        round: "Asian Cup Grp. E - Matchday 2",
        homeTeam_id: "1551",
        awayTeam_id: "23",
        homeTeam: "Lebanon",
        awayTeam: "Saudi Arabia",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "37743": {
        fixture_id: "37743",
        event_timestamp: "1547308800",
        event_date: "2019-01-12T16:00:00+00:00",
        league_id: "4",
        round: "Ligue 1 - 20",
        homeTeam_id: "87",
        awayTeam_id: "85",
        homeTeam: "Amiens",
        awayTeam: "Paris Saint Germain",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "65924": {
        fixture_id: "65924",
        event_timestamp: "1547312400",
        event_date: "2019-01-12T17:00:00+00:00",
        league_id: "198",
        round: "Third Round - 1/8",
        homeTeam_id: "498",
        awayTeam_id: "489",
        homeTeam: "Sampdoria",
        awayTeam: "AC Milan",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "278": {
        fixture_id: "278",
        event_timestamp: "1547314200",
        event_date: "2019-01-12T17:30:00+00:00",
        league_id: "2",
        round: "Premier League - 22",
        homeTeam_id: "49",
        awayTeam_id: "34",
        homeTeam: "Chelsea",
        awayTeam: "Newcastle",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "37744": {
        fixture_id: "37744",
        event_timestamp: "1547319600",
        event_date: "2019-01-12T19:00:00+00:00",
        league_id: "4",
        round: "Ligue 1 - 20",
        homeTeam_id: "88",
        awayTeam_id: "79",
        homeTeam: "Caen",
        awayTeam: "Lille",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "51288": {
        fixture_id: "51288",
        event_timestamp: "1547319600",
        event_date: "2019-01-12T19:00:00+00:00",
        league_id: "173",
        round: "Closing Tournament - Round 7",
        homeTeam_id: "264",
        awayTeam_id: "263",
        homeTeam: "Roeselare",
        awayTeam: "Beerschot Wilrijk",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "37751": {
        fixture_id: "37751",
        event_timestamp: "1547319600",
        event_date: "2019-01-12T19:00:00+00:00",
        league_id: "4",
        round: "Ligue 1 - 20",
        homeTeam_id: "92",
        awayTeam_id: "77",
        homeTeam: "Nimes",
        awayTeam: "Angers",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "37750": {
        fixture_id: "37750",
        event_timestamp: "1547319600",
        event_date: "2019-01-12T19:00:00+00:00",
        league_id: "4",
        round: "Ligue 1 - 20",
        homeTeam_id: "84",
        awayTeam_id: "78",
        homeTeam: "Nice",
        awayTeam: "Bordeaux",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "37745": {
        fixture_id: "37745",
        event_timestamp: "1547319600",
        event_date: "2019-01-12T19:00:00+00:00",
        league_id: "4",
        round: "Ligue 1 - 20",
        homeTeam_id: "89",
        awayTeam_id: "82",
        homeTeam: "Dijon",
        awayTeam: "Montpellier",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "45124": {
        fixture_id: "45124",
        event_timestamp: "1547319600",
        event_date: "2019-01-12T19:00:00+00:00",
        league_id: "156",
        round: "National - Round 18",
        homeTeam_id: "433",
        awayTeam_id: "1299",
        homeTeam: "Laval",
        awayTeam: "Boulogne",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: "",
        goalsAwayTeam: "",
        halftime_score: null,
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "37746": {
        fixture_id: "37746",
        event_timestamp: "1547319600",
        event_date: "2019-01-12T19:00:00+00:00",
        league_id: "4",
        round: "Ligue 1 - 20",
        homeTeam_id: "90",
        awayTeam_id: "1063",
        homeTeam: "Guingamp",
        awayTeam: "Saint Etienne",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      },
      "65925": {
        fixture_id: "65925",
        event_timestamp: "1547322300",
        event_date: "2019-01-12T19:45:00+00:00",
        league_id: "198",
        round: "Third Round - 1/8",
        homeTeam_id: "500",
        awayTeam_id: "496",
        homeTeam: "Bologna",
        awayTeam: "Juventus",
        status: "Not Started",
        statusShort: "NS",
        goalsHomeTeam: null,
        goalsAwayTeam: null,
        halftime_score: "-",
        final_score: null,
        penalty: null,
        elapsed: "0",
        firstHalfStart: "0",
        secondHalfStart: "0"
      }
    }
  }
};
